# Generated by Django 3.0.6 on 2020-05-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
