# Generated by Django 3.0.6 on 2020-05-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200515_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
